# Generated by Django 5.0.1 on 2024-02-07 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_productimage_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsproduct',
            old_name='image',
            new_name='images',
        ),
    ]
