# Generated by Django 5.0.1 on 2024-02-07 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_rename_image_newsproduct_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsproduct',
            old_name='images',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='images',
        ),
    ]
