# Generated by Django 5.0.1 on 2024-02-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_rename_images_newsproduct_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
