# Generated by Django 5.0.1 on 2024-02-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='star',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
