# Generated by Django 5.0.1 on 2024-02-17 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_alter_shoper_numberpraduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoper',
            name='save',
        ),
    ]
